version: '3.8'

volumes:
  local_postgres_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: hospital_db_postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres
    ports:
      - "5433:5432"

  client:
    build: 
      context: .
      dockerfile: ./compose/client/Dockerfile
    image: hospital_db_client
    env_file:
      - .envs/.pg_admin
    ports:
      - "80:80"
    depends_on:
      - postgres
